### ISSUE TITLE
FileName.mb.ma && installation guide

### ISSUE THREAD

**Issue by djkato** [ArhasGH/Discord-Rich-Presence-For-Maya#3]
Hello! Thank you for this extention, its great! But theres a few things I want to request :)
Version : Maya 2020
first of all Im not sure how the file extention is handelled but if I work on something in .mb then it adds another .ma at the end:
![image](https://user-images.githubusercontent.com/25299243/103464563-f8a2f780-4d34-11eb-8770-dfbc83acdb8c.png)
![image](https://user-images.githubusercontent.com/25299243/103464565-0193c900-4d35-11eb-9f24-6e40862c4a6f.png)
Also the front page instructions are a little misleading, or atleast for the newest 2020 version. in the 2020 version the plug-in folder is located in 
C:\Program Files\Autodesk\Maya2020\bin\plug-ins
instead of in Documents. Maybe it used to work like that, maybe it does but it didnt show up for me until I put the .mll file there and enabled it in plugin manager :) 
Otherwise, its great.
Thanks, dj

**Comment by ArhasGH** [comment]
I'll be honest I simply forgot that .mb exists and didn't implement it. Should be fixed now. The instructions have also been updated accordingly, thx for the feedback!
